//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnyras
    {
        public int TurnyroID { get; set; }
        public string TurnyroPavadinimas { get; set; }
        public string TurnyroVieta { get; set; }
        public string TurnyroData { get; set; }
    }
}
